package gt.gob.sat.fiscalizacion.consulta360.modelo;
// Generated 27-nov-2021 13:05:56 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CifClasesDeclaraciones generated by hbm2java
 */
@Entity
@Table(name = "CIF_CLASES_DECLARACIONES",
         schema = "SAT_FISCALIZACION"
)
public class CifClasesDeclaraciones implements java.io.Serializable {

    private BigDecimal idReporte;
    private String nombre;
    private String descripcion;
    private String usuarioCreacion;
    private Date fechaCreacion;
    private Set<CifDeclaracionesPresentadas> cifDeclaracionesPresentadases = new HashSet<>(0);

    public CifClasesDeclaraciones() {
    }

    public CifClasesDeclaraciones(BigDecimal idReporte, String nombre) {
        this.idReporte = idReporte;
        this.nombre = nombre;
    }

    public CifClasesDeclaraciones(BigDecimal idReporte, String nombre, String descripcion, String usuarioCreacion, Date fechaCreacion, Set<CifDeclaracionesPresentadas> cifDeclaracionesPresentadases) {
        this.idReporte = idReporte;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.usuarioCreacion = usuarioCreacion;
        this.fechaCreacion = fechaCreacion;
        this.cifDeclaracionesPresentadases = cifDeclaracionesPresentadases;
    }

    @Id
    @Column(name = "ID_REPORTE", unique = true, nullable = false, precision = 22, scale = 0)
    public BigDecimal getIdReporte() {
        return this.idReporte;
    }

    public void setIdReporte(BigDecimal idReporte) {
        this.idReporte = idReporte;
    }

    @Column(name = "NOMBRE", nullable = false, length = 200)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "DESCRIPCION", length = 500)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "USUARIO_CREACION", length = 50)
    public String getUsuarioCreacion() {
        return this.usuarioCreacion;
    }

    public void setUsuarioCreacion(String usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "FECHA_CREACION", length = 7)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cifClasesDeclaraciones")
    public Set<CifDeclaracionesPresentadas> getCifDeclaracionesPresentadases() {
        return this.cifDeclaracionesPresentadases;
    }

    public void setCifDeclaracionesPresentadases(Set<CifDeclaracionesPresentadas> cifDeclaracionesPresentadases) {
        this.cifDeclaracionesPresentadases = cifDeclaracionesPresentadases;
    }

}
