package gt.gob.sat.fiscalizacion.consulta360.modelo;
// Generated 20/06/2022 12:59:46 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CifCargaVerificacionesCampo generated by hbm2java
 */
@Entity
@Table(name = "CIF_CARGA_VERIFICACIONES_CAMPO",
        schema = "SAT_FISCALIZACION"
)
public class CifCargaVerificacionesCampo implements java.io.Serializable {

    private BigDecimal idCargaCampo;
    private String nombreArchivo;
    private Date fechaCargaRegistro;
    private BigDecimal cantidadRegistrosCargados;
    private String usuarioRegistro;
    private Blob documentoArchivo;

    public CifCargaVerificacionesCampo() {
    }

    public CifCargaVerificacionesCampo(BigDecimal idCargaCampo) {
        this.idCargaCampo = idCargaCampo;
    }

    public CifCargaVerificacionesCampo(BigDecimal idCargaCampo, String nombreArchivo, Date fechaCargaRegistro, BigDecimal cantidadRegistrosCargados, String usuarioRegistro, Blob documentoArchivo) {
        this.idCargaCampo = idCargaCampo;
        this.nombreArchivo = nombreArchivo;
        this.fechaCargaRegistro = fechaCargaRegistro;
        this.cantidadRegistrosCargados = cantidadRegistrosCargados;
        this.usuarioRegistro = usuarioRegistro;
        this.documentoArchivo = documentoArchivo;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "carga_verificaciones_campo")
    @SequenceGenerator(name = "carga_verificaciones_campo", sequenceName = "SEQ_CARGA_VERIFICACIONES_CAMPO", allocationSize = 0)
    
    @Column(name = "ID_CARGA_CAMPO", unique = true, nullable = false, precision = 22, scale = 0)
    public BigDecimal getIdCargaCampo() {
        return this.idCargaCampo;
    }

    public void setIdCargaCampo(BigDecimal idCargaCampo) {
        this.idCargaCampo = idCargaCampo;
    }

    @Column(name = "NOMBRE_ARCHIVO", length = 100)
    public String getNombreArchivo() {
        return this.nombreArchivo;
    }

    public void setNombreArchivo(String nombreArchivo) {
        this.nombreArchivo = nombreArchivo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "FECHA_CARGA_REGISTRO", length = 7)
    public Date getFechaCargaRegistro() {
        return this.fechaCargaRegistro;
    }

    public void setFechaCargaRegistro(Date fechaCargaRegistro) {
        this.fechaCargaRegistro = fechaCargaRegistro;
    }

    @Column(name = "CANTIDAD_REGISTROS_CARGADOS", precision = 22, scale = 0)
    public BigDecimal getCantidadRegistrosCargados() {
        return this.cantidadRegistrosCargados;
    }

    public void setCantidadRegistrosCargados(BigDecimal cantidadRegistrosCargados) {
        this.cantidadRegistrosCargados = cantidadRegistrosCargados;
    }

    @Column(name = "USUARIO_REGISTRO", length = 45)
    public String getUsuarioRegistro() {
        return this.usuarioRegistro;
    }

    public void setUsuarioRegistro(String usuarioRegistro) {
        this.usuarioRegistro = usuarioRegistro;
    }

    @Column(name = "DOCUMENTO_ARCHIVO")
    public Blob getDocumentoArchivo() {
        return this.documentoArchivo;
    }

    public void setDocumentoArchivo(Blob documentoArchivo) {
        this.documentoArchivo = documentoArchivo;
    }

}
