package gt.gob.sat.fiscalizacion.consulta360.modelo;
// Generated 27-nov-2021 13:05:56 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CifDeclaracionesPresentadas generated by hbm2java
 */
@Entity
@Table(name = "CIF_DECLARACIONES_PRESENTADAS",
         schema = "SAT_FISCALIZACION"
)
public class CifDeclaracionesPresentadas implements java.io.Serializable {

    private BigDecimal id;
    private CifClasesDeclaraciones cifClasesDeclaraciones;
    private String descripcion;
    private String observaciones;
    private String usuarioCreacion;
    private Date fechaCreacion;

    public CifDeclaracionesPresentadas() {
    }

    public CifDeclaracionesPresentadas(BigDecimal id, CifClasesDeclaraciones cifClasesDeclaraciones) {
        this.id = id;
        this.cifClasesDeclaraciones = cifClasesDeclaraciones;
    }

    public CifDeclaracionesPresentadas(BigDecimal id, CifClasesDeclaraciones cifClasesDeclaraciones, String descripcion, String observaciones, String usuarioCreacion, Date fechaCreacion) {
        this.id = id;
        this.cifClasesDeclaraciones = cifClasesDeclaraciones;
        this.descripcion = descripcion;
        this.observaciones = observaciones;
        this.usuarioCreacion = usuarioCreacion;
        this.fechaCreacion = fechaCreacion;
    }

    @Id
    @Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
    public BigDecimal getId() {
        return this.id;
    }

    public void setId(BigDecimal id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_REPORTE", nullable = false)
    public CifClasesDeclaraciones getCifClasesDeclaraciones() {
        return this.cifClasesDeclaraciones;
    }

    public void setCifClasesDeclaraciones(CifClasesDeclaraciones cifClasesDeclaraciones) {
        this.cifClasesDeclaraciones = cifClasesDeclaraciones;
    }

    @Column(name = "DESCRIPCION", length = 1500)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "OBSERVACIONES", length = 500)
    public String getObservaciones() {
        return this.observaciones;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    @Column(name = "USUARIO_CREACION", length = 50)
    public String getUsuarioCreacion() {
        return this.usuarioCreacion;
    }

    public void setUsuarioCreacion(String usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "FECHA_CREACION", length = 7)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

}
