package gt.gob.sat.fiscalizacion.consulta360.modelo;
// Generated 20/06/2022 12:15:33 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CifTipologiasDeEvasion generated by hbm2java
 */
@Entity
@Table(name="CIF_TIPOLOGIAS_DE_EVASION"
    ,schema="SAT_FISCALIZACION"
)
public class CifTipologiasDeEvasion  implements java.io.Serializable {


     private BigDecimal id;
     private BigDecimal idTipologia;
     private String nit;
     private String referencia;
     private Date fechaRegistro;
     private String descripcionTipologia;
     private BigDecimal anioInformacion;
     private BigDecimal indicador;
     private String colorIndicador;
     private BigDecimal montoDiscrepancia;
     private String dependencia;
     private String estado;
     private Date fechaEstado;
     private String observacionesEstado;

    public CifTipologiasDeEvasion() {
    }

	
    public CifTipologiasDeEvasion(BigDecimal id, BigDecimal idTipologia, String nit, Date fechaRegistro, String descripcionTipologia, String estado) {
        this.id = id;
        this.idTipologia = idTipologia;
        this.nit = nit;
        this.fechaRegistro = fechaRegistro;
        this.descripcionTipologia = descripcionTipologia;
        this.estado = estado;
    }
    public CifTipologiasDeEvasion(BigDecimal id, BigDecimal idTipologia, String nit, String referencia, Date fechaRegistro, String descripcionTipologia, BigDecimal anioInformacion, BigDecimal indicador, String colorIndicador, BigDecimal montoDiscrepancia, String dependencia, String estado, Date fechaEstado, String observacionesEstado) {
       this.id = id;
       this.idTipologia = idTipologia;
       this.nit = nit;
       this.referencia = referencia;
       this.fechaRegistro = fechaRegistro;
       this.descripcionTipologia = descripcionTipologia;
       this.anioInformacion = anioInformacion;
       this.indicador = indicador;
       this.colorIndicador = colorIndicador;
       this.montoDiscrepancia = montoDiscrepancia;
       this.dependencia = dependencia;
       this.estado = estado;
       this.fechaEstado = fechaEstado;
       this.observacionesEstado = observacionesEstado;
    }
   
     @Id
     @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "carga_tipologia")
     @SequenceGenerator(name = "carga_tipologia", sequenceName = "CIF_SEQ_TIP_DE_EVASION", allocationSize = 0)

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

    
    @Column(name="ID_TIPOLOGIA", nullable=false, precision=22, scale=0)
    public BigDecimal getIdTipologia() {
        return this.idTipologia;
    }
    
    public void setIdTipologia(BigDecimal idTipologia) {
        this.idTipologia = idTipologia;
    }

    
    @Column(name="NIT", nullable=false, length=15)
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }

    
    @Column(name="REFERENCIA", length=100)
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_REGISTRO", nullable=false, length=7)
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    
    @Column(name="DESCRIPCION_TIPOLOGIA", nullable=false, length=500)
    public String getDescripcionTipologia() {
        return this.descripcionTipologia;
    }
    
    public void setDescripcionTipologia(String descripcionTipologia) {
        this.descripcionTipologia = descripcionTipologia;
    }

    
    @Column(name="ANIO_INFORMACION", precision=22, scale=0)
    public BigDecimal getAnioInformacion() {
        return this.anioInformacion;
    }
    
    public void setAnioInformacion(BigDecimal anioInformacion) {
        this.anioInformacion = anioInformacion;
    }

    
    @Column(name="INDICADOR", precision=8)
    public BigDecimal getIndicador() {
        return this.indicador;
    }
    
    public void setIndicador(BigDecimal indicador) {
        this.indicador = indicador;
    }

    
    @Column(name="COLOR_INDICADOR", length=20)
    public String getColorIndicador() {
        return this.colorIndicador;
    }
    
    public void setColorIndicador(String colorIndicador) {
        this.colorIndicador = colorIndicador;
    }

    
    @Column(name="MONTO_DISCREPANCIA", precision=12)
    public BigDecimal getMontoDiscrepancia() {
        return this.montoDiscrepancia;
    }
    
    public void setMontoDiscrepancia(BigDecimal montoDiscrepancia) {
        this.montoDiscrepancia = montoDiscrepancia;
    }

    
    @Column(name="DEPENDENCIA", length=100)
    public String getDependencia() {
        return this.dependencia;
    }
    
    public void setDependencia(String dependencia) {
        this.dependencia = dependencia;
    }

    
    @Column(name="ESTADO", nullable=false, length=1)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_ESTADO", length=7)
    public Date getFechaEstado() {
        return this.fechaEstado;
    }
    
    public void setFechaEstado(Date fechaEstado) {
        this.fechaEstado = fechaEstado;
    }

    
    @Column(name="OBSERVACIONES_ESTADO", length=550)
    public String getObservacionesEstado() {
        return this.observacionesEstado;
    }
    
    public void setObservacionesEstado(String observacionesEstado) {
        this.observacionesEstado = observacionesEstado;
    }




}


