package gt.gob.sat.fiscalizacion.consulta360.modelo;
// Generated 13-jul-2021 8:07:20 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CifVerificacionesEnCampo generated by hbm2java
 */
@Entity
@Table(name="CIF_VERIFICACIONES_EN_CAMPO"
    ,schema="SAT_FISCALIZACION"
)
public class CifVerificacionesEnCampo  implements java.io.Serializable {


     private BigDecimal id;
     private String nit;
     private String contribuyente;
     private String direccionVerificada;
     private String departamento;
     private String municipio;
     private BigDecimal longitud;
     private BigDecimal latitud;
     private String tipoDireccion;
     private String estadoDireccion;
     private String fuenteDeInformacion;
     private String estimacionCapacidadInstalada;
     private String contadorEnergiaElectrica;
     private String referenciaVerificacion;
     private String responsableDeLaVerificacion;
     private String estadoRegistro;
     private Date fechaCreacion;

    public CifVerificacionesEnCampo() {
    }

	
    public CifVerificacionesEnCampo(BigDecimal id, String nit, String contribuyente, String departamento, String municipio, String tipoDireccion, String estadoDireccion, String fuenteDeInformacion, String referenciaVerificacion, String estadoRegistro, Date fechaCreacion) {
        this.id = id;
        this.nit = nit;
        this.contribuyente = contribuyente;
        this.departamento = departamento;
        this.municipio = municipio;
        this.tipoDireccion = tipoDireccion;
        this.estadoDireccion = estadoDireccion;
        this.fuenteDeInformacion = fuenteDeInformacion;
        this.referenciaVerificacion = referenciaVerificacion;
        this.estadoRegistro = estadoRegistro;
        this.fechaCreacion = fechaCreacion;
    }
    public CifVerificacionesEnCampo(BigDecimal id, String nit, String contribuyente, String direccionVerificada, String departamento, String municipio, BigDecimal longitud, BigDecimal latitud, String tipoDireccion, String estadoDireccion, String fuenteDeInformacion, String estimacionCapacidadInstalada, String contadorEnergiaElectrica, String referenciaVerificacion, String responsableDeLaVerificacion, String estadoRegistro, Date fechaCreacion) {
       this.id = id;
       this.nit = nit;
       this.contribuyente = contribuyente;
       this.direccionVerificada = direccionVerificada;
       this.departamento = departamento;
       this.municipio = municipio;
       this.longitud = longitud;
       this.latitud = latitud;
       this.tipoDireccion = tipoDireccion;
       this.estadoDireccion = estadoDireccion;
       this.fuenteDeInformacion = fuenteDeInformacion;
       this.estimacionCapacidadInstalada = estimacionCapacidadInstalada;
       this.contadorEnergiaElectrica = contadorEnergiaElectrica;
       this.referenciaVerificacion = referenciaVerificacion;
       this.responsableDeLaVerificacion = responsableDeLaVerificacion;
       this.estadoRegistro = estadoRegistro;
       this.fechaCreacion = fechaCreacion;
    }
    
    
    @Id
     @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "verificaciones_campo")
     @SequenceGenerator(name = "verificaciones_campo", sequenceName = "CIF_SEQ_VER_EN_CAMPO", allocationSize = 0)



    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

    
    @Column(name="NIT", nullable=false, length=15)
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }

    
    @Column(name="CONTRIBUYENTE", nullable=false, length=150)
    public String getContribuyente() {
        return this.contribuyente;
    }
    
    public void setContribuyente(String contribuyente) {
        this.contribuyente = contribuyente;
    }

    
    @Column(name="DIRECCION_VERIFICADA", length=300)
    public String getDireccionVerificada() {
        return this.direccionVerificada;
    }
    
    public void setDireccionVerificada(String direccionVerificada) {
        this.direccionVerificada = direccionVerificada;
    }

    
    @Column(name="DEPARTAMENTO", nullable=false, length=100)
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }

    
    @Column(name="MUNICIPIO", nullable=false, length=100)
    public String getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(String municipio) {
        this.municipio = municipio;
    }

    
    @Column(name="LONGITUD", precision=22, scale=0)
    public BigDecimal getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(BigDecimal longitud) {
        this.longitud = longitud;
    }

    
    @Column(name="LATITUD", precision=22, scale=0)
    public BigDecimal getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(BigDecimal latitud) {
        this.latitud = latitud;
    }

    
    @Column(name="TIPO_DIRECCION", nullable=false, length=100)
    public String getTipoDireccion() {
        return this.tipoDireccion;
    }
    
    public void setTipoDireccion(String tipoDireccion) {
        this.tipoDireccion = tipoDireccion;
    }

    
    @Column(name="ESTADO_DIRECCION", nullable=false, length=50)
    public String getEstadoDireccion() {
        return this.estadoDireccion;
    }
    
    public void setEstadoDireccion(String estadoDireccion) {
        this.estadoDireccion = estadoDireccion;
    }

    
    @Column(name="FUENTE_DE_INFORMACION", nullable=false, length=100)
    public String getFuenteDeInformacion() {
        return this.fuenteDeInformacion;
    }
    
    public void setFuenteDeInformacion(String fuenteDeInformacion) {
        this.fuenteDeInformacion = fuenteDeInformacion;
    }

    
    @Column(name="ESTIMACION_CAPACIDAD_INSTALADA", length=100)
    public String getEstimacionCapacidadInstalada() {
        return this.estimacionCapacidadInstalada;
    }
    
    public void setEstimacionCapacidadInstalada(String estimacionCapacidadInstalada) {
        this.estimacionCapacidadInstalada = estimacionCapacidadInstalada;
    }

    
    @Column(name="CONTADOR_ENERGIA_ELECTRICA", length=50)
    public String getContadorEnergiaElectrica() {
        return this.contadorEnergiaElectrica;
    }
    
    public void setContadorEnergiaElectrica(String contadorEnergiaElectrica) {
        this.contadorEnergiaElectrica = contadorEnergiaElectrica;
    }

    
    @Column(name="REFERENCIA_VERIFICACION", nullable=false, length=50)
    public String getReferenciaVerificacion() {
        return this.referenciaVerificacion;
    }
    
    public void setReferenciaVerificacion(String referenciaVerificacion) {
        this.referenciaVerificacion = referenciaVerificacion;
    }

    
    @Column(name="RESPONSABLE_DE_LA_VERIFICACION", length=100)
    public String getResponsableDeLaVerificacion() {
        return this.responsableDeLaVerificacion;
    }
    
    public void setResponsableDeLaVerificacion(String responsableDeLaVerificacion) {
        this.responsableDeLaVerificacion = responsableDeLaVerificacion;
    }

    
    @Column(name="ESTADO_REGISTRO", nullable=false, length=1)
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_CREACION", nullable=false, length=7)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }




}


