package gt.gob.sat.fiscalizacion.consulta360.modelo;
// Generated 16/08/2018 03:06:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Consulta360BitacoraId generated by hbm2java
 */
@Embeddable
public class Consulta360BitacoraId  implements java.io.Serializable {


     private BigDecimal paginaConsultada;
     private String nitConsultado;
     private Date fechaConsulto;
     private String nitConsulto;
     private String ipConsulto;

    public Consulta360BitacoraId() {
    }

    public Consulta360BitacoraId(BigDecimal paginaConsultada, String nitConsultado, Date fechaConsulto, String nitConsulto, String ipConsulto) {
       this.paginaConsultada = paginaConsultada;
       this.nitConsultado = nitConsultado;
       this.fechaConsulto = fechaConsulto;
       this.nitConsulto = nitConsulto;
       this.ipConsulto = ipConsulto;
    }
   


    @Column(name="PAGINA_CONSULTADA", nullable=false, precision=22, scale=0)
    public BigDecimal getPaginaConsultada() {
        return this.paginaConsultada;
    }
    
    public void setPaginaConsultada(BigDecimal paginaConsultada) {
        this.paginaConsultada = paginaConsultada;
    }


    @Column(name="NIT_CONSULTADO", nullable=false, length=12)
    public String getNitConsultado() {
        return this.nitConsultado;
    }
    
    public void setNitConsultado(String nitConsultado) {
        this.nitConsultado = nitConsultado;
    }


    @Column(name="FECHA_CONSULTO", nullable=false, length=7)
    public Date getFechaConsulto() {
        return this.fechaConsulto;
    }
    
    public void setFechaConsulto(Date fechaConsulto) {
        this.fechaConsulto = fechaConsulto;
    }


    @Column(name="NIT_CONSULTO", nullable=false, length=12)
    public String getNitConsulto() {
        return this.nitConsulto;
    }
    
    public void setNitConsulto(String nitConsulto) {
        this.nitConsulto = nitConsulto;
    }


    @Column(name="IP_CONSULTO", nullable=false, length=23)
    public String getIpConsulto() {
        return this.ipConsulto;
    }
    
    public void setIpConsulto(String ipConsulto) {
        this.ipConsulto = ipConsulto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Consulta360BitacoraId) ) return false;
		 Consulta360BitacoraId castOther = ( Consulta360BitacoraId ) other; 
         
		 return ( (this.getPaginaConsultada()==castOther.getPaginaConsultada()) || ( this.getPaginaConsultada()!=null && castOther.getPaginaConsultada()!=null && this.getPaginaConsultada().equals(castOther.getPaginaConsultada()) ) )
 && ( (this.getNitConsultado()==castOther.getNitConsultado()) || ( this.getNitConsultado()!=null && castOther.getNitConsultado()!=null && this.getNitConsultado().equals(castOther.getNitConsultado()) ) )
 && ( (this.getFechaConsulto()==castOther.getFechaConsulto()) || ( this.getFechaConsulto()!=null && castOther.getFechaConsulto()!=null && this.getFechaConsulto().equals(castOther.getFechaConsulto()) ) )
 && ( (this.getNitConsulto()==castOther.getNitConsulto()) || ( this.getNitConsulto()!=null && castOther.getNitConsulto()!=null && this.getNitConsulto().equals(castOther.getNitConsulto()) ) )
 && ( (this.getIpConsulto()==castOther.getIpConsulto()) || ( this.getIpConsulto()!=null && castOther.getIpConsulto()!=null && this.getIpConsulto().equals(castOther.getIpConsulto()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPaginaConsultada() == null ? 0 : this.getPaginaConsultada().hashCode() );
         result = 37 * result + ( getNitConsultado() == null ? 0 : this.getNitConsultado().hashCode() );
         result = 37 * result + ( getFechaConsulto() == null ? 0 : this.getFechaConsulto().hashCode() );
         result = 37 * result + ( getNitConsulto() == null ? 0 : this.getNitConsulto().hashCode() );
         result = 37 * result + ( getIpConsulto() == null ? 0 : this.getIpConsulto().hashCode() );
         return result;
   }   


}


