package gt.gob.sat.fiscalizacion.consulta360.modelo;
// Generated 16/08/2018 03:06:03 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Consulta360Bitacora generated by hbm2java
 */
@Entity
@Table(name="CONSULTA360_BITACORA"
    ,schema="SAT_FISCALIZACION"
)
public class Consulta360Bitacora  implements java.io.Serializable {


     private Consulta360BitacoraId id;

    public Consulta360Bitacora() {
    }

    public Consulta360Bitacora(Consulta360BitacoraId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="paginaConsultada", column=@Column(name="PAGINA_CONSULTADA", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="nitConsultado", column=@Column(name="NIT_CONSULTADO", nullable=false, length=12) ), 
        @AttributeOverride(name="fechaConsulto", column=@Column(name="FECHA_CONSULTO", nullable=false, length=7) ), 
        @AttributeOverride(name="nitConsulto", column=@Column(name="NIT_CONSULTO", nullable=false, length=12) ), 
        @AttributeOverride(name="ipConsulto", column=@Column(name="IP_CONSULTO", nullable=false, length=23) ) } )
    public Consulta360BitacoraId getId() {
        return this.id;
    }
    
    public void setId(Consulta360BitacoraId id) {
        this.id = id;
    }




}


